namespace ClashofClans.Logic.Home.Slots.Items
{
    public enum VariableSlot
    {
        StarBonusCounter,
        StarBonusCooldown,
        StarBonusTimerEndSubTick,
        StarBonusTimerEndTimestep,
        StarBonusTimesCollected,
        ChallengeStarted,
        ChallengeLayoutIsWar,
        FriendListLastOpened,
        BeenInArrangedWar,
        FILL_ME,
        AccountBound,
        EventUseTroop,
        VillageToGoTo,
        LootLimitWinCount,
        LootLimitTimerEndSubTick,
        LootLimitTimerEndTimestamp,
        LootLimitCooldown,
        Village2BarrackLevel,
        LootLimitFreeSpeedUp,
        SeenBuilderMenu,
        MaxArmyTimerEndSubTick,
        MaxArmyTimerEndTimeStamp,
        MaxArmyTimerPausedTicksLeft
    }
}
